custom_signup/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'home#index'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :categories do
    collection do
      get :autocompleter
    end
  end

end

custom_signup/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true

  def self.user_categories_by_keyword(user, keyword)
    user.categories.where("LOWER(name) LIKE LOWER(?)", "%#{keyword}%").all
  end

end

custom_signup/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :categories

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    self.update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

custom_signup/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

custom_signup/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    if params[:keyword]
      @categories = Category.user_categories_by_keyword(current_user, params[:keyword])
    else
      @categories = current_user.categories.all
    end

    if request.xhr?
      html = render_to_string(:partial => 'categories/categories_listing', :layout => false, :locals => {categories: @categories})
      render json: {success: true, html: html} and return
    end
  end

  def autocompleter
    categories = Category.user_categories_by_keyword(current_user, params[:keyword]).collect{|cat| cat.name}
    render json: categories
  end

  def show
    @category = current_user.categories.where(id: params[:id])
    if @category.blank?
      flash[:danger] = 'Invalid category id.'
      redirect :back
    end
  end

  def create
    begin
      @category = current_user.categories.create!(name: params[:name])
    rescue ActiveRecord::RecordNotUnique => ex
      error = "Record Not Unique"
    rescue Exception => ex
      error = ex.message
    end
    if error.blank?
      render json: {success: true, message: 'Successfully created category'}
    else
      render json: {success: true, message: error}
    end
  end

  def edit

  end

  def update
    category = current_user.categories.find_by(id: params[:id])
    render json: {success: false, message: 'Invalid category'} and return if category.blank?

    category.name = params[:name]
    begin
      category.save!
    rescue ActiveRecord::RecordNotUnique => ex
      error = "Record Not Unique"
    rescue Exception => ex
      error = ex.message
    end
    if error.blank?
      render json: {success: true, message: 'Successfully updated category.'}
    else
      render json: {success: false, message: error}
    end
  end

  def destroy
    category = current_user.categories.find_by(id: params[:id])
    render json: {success: false, message: 'Invalid category'} and return if category.blank?

    if category.destroy
      render json: {success: true, message: 'Successfully deleted category.'}
    else
      render json: {success: false, message: category.errors.full_messages.join(',')}
    end
  end
end

custom_signup/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to categories_path and return
    end
  end
end

custom_signup/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash[:danger] = 'Invalid email/password combination.'
      render 'new'
    end

  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private
  def create_params
    params.require(:session).permit(:email, :password, :remember_me)
  end
end

custom_signup/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :show]
  before_action :correct_user, only: [:edit, :update, :show]

  def index
    @users = User.all.includes(:categories)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Signed up successfully.'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user.blank?
      flash[:danger] ='User does not exist.'
      redirect_to '/'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    if @user.blank?
      flash[:danger] ='User does not exist.'
      redirect_to '/'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


    # Confirms the correct user.
    def correct_user
      @user = User.find_by(id: params[:id])
      unless current_user?(@user)
        flash[:danger] = "You do not have priviledge to take this action."
        redirect_to(root_url)
      end
    end
end

custom_signup/app/helpers/application_helper.rb
module ApplicationHelper
end

custom_signup/app/helpers/categories_helper.rb
module CategoriesHelper
end

custom_signup/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

custom_signup/app/views/home/index.html.erb
<% if logged_in? %>

<% else %>
    <div class="center jumbotron">
      <h1>Welcome to the My space</h1>

      <h2>
        This is the home page for the custom signup application
      </h2>

      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

custom_signup/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by <a href="https://indyarock.wordpress.com/">Chandan Kumar</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

custom_signup/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Custom Signup", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

custom_signup/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

custom_signup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "Custon Signup" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <a href="http://www.flipkart.com/bs-spy-electronic-heating-pad-electrical-2-l-hot-water-bag/p/itme9zcb4huatke2?pid=HWBE9ZCAJ5CZBFJP&affid=nimishajh">Bs Spy Electronic Heating Pad Electrical 2 L Hot Water Bag</a>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

custom_signup/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

custom_signup/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

custom_signup/app/views/users/index.html.erb
<% provide(:title, 'User profile') %>
<h1>User listing</h1>

<div class="container">
<table class="table table-striped">
  <thead>
  <tr>
    <th>User Id</th>
    <th>Name</th>
    <th>Email</th>
    <th>Categories Created</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.categories.count %></td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

custom_signup/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

custom_signup/app/views/users/show.html.erb
<% provide(:title, 'User profile') %>
<h1>Welcome <%= @user.name %></h1>

<div class="center">
  <ul style="list-style-type: none;">
    <li>Name: <%= @user.name %></li>
    <li>Email: <%= @user.email %></li>
  </ul>
</div>