trip_planner/config/routes.rb
Rails.application.routes.draw do
  resources :train_schedules

  root 'home_page#home'

  get 'trip-type' => 'home_page#get_trip_type', as: 'trip_type'

  get 'search_result-trip' => 'home_page#search_trip', as: 'search_trip'

  resources :trains

  resources :stations

end

trip_planner/app/models/train_schedule.rb
class TrainSchedule < ActiveRecord::Base
  validates :train_number, inclusion: { in: Train.valid_train_numbers, :message => "Invalid train number."}
  validates :station_code, inclusion: { in: Station.valid_station_codes, :message => "Invalid station code."}

  validates_uniqueness_of :train_number, scope: :station_code, message: "The train number and station code combination already exists."

  validates :sun, :mon, :tue, :wed, :thu, :fri, :sat, :inclusion => {:in => [true, false], :message => "Invalid weekday input" }
  validates :journey_day, numericality: { greater_than_or_equal_to: 1, :message => "Journey day must be greater than or equal to 1."}


  VALID_TIME_FORMAT_REGEX = /\A(([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9])|(n\/a)\z/i
  validates :arrival_time, format: { with: VALID_TIME_FORMAT_REGEX, :message => "Arrival time must be a valid time in HH:MM format or N/A for origin"}
  validates :departure_time, format: { with: VALID_TIME_FORMAT_REGEX, :message => "Departure time must be a valid time in HH:MM format or N/A for end point"}

  VALID_TRIP_TYPES = %w(one_way return multi_part).freeze

  WDAY_DAY_MAP = { 0 => 'sun', 1 => 'mon', 2 => 'tue', 3 => 'wed', 4 => 'thu', 5 => 'fri', 6 => 'sat'}.freeze


  # Method to find the trip details
  #
  # <b>Expects</b>
  #   <b>Hash[:trip_type]</b> <em>(String)</em> - Valid trip type from VALID_TRIP_TYPES
  #   <b>Hash[:origin]</b> <em>(String)</em> - Valid station code - for one-way and return journey
  #   <b>Hash[:origin_1]</b> <em>(String)</em> - Valid station code - for multi-part journey
  #   <b>Hash[:origin_2]</b> <em>(String)</em> - Valid station code - for multi-part journey
  #   <b>Hash[:destination]</b> <em>(String)</em> - Valid station code - for one-way and return journey
  #   <b>Hash[:destination_1]</b> <em>(String)</em> - Valid station code - for multi-part journey
  #   <b>Hash[:destination_2]</b> <em>(String)</em> - Valid station code - for multi-part journey
  #   <b>Hash[:depart_date]</b> <em>(String)</em> - Valid depart date - for one-way and return journey
  #   <b>Hash[:depart_date_1]</b> <em>(String)</em> - Valid depart date - for multi-part journey
  #   <b>Hash[:depart_date_2]</b> <em>(String)</em> - Valid depart date - for multi-part journey
  #
  # <b>Returns</b>
  #   <b>Hash[:trip_details][:single_trains]</b> <em>(Array)</em> Array of single trip details
  #   <b>Hash[:trip_details][:multi_part]</b><em>(Array)</em> Array of Array having multi part trip details
  #   <b>Hash[:err]</b><em>(String)</em> Error code, if any
  #   <b>Hash[:message]</b><em>(String)</em> Error message, if any
  #
  #
  def self.find_suitable_trip_schedule(params)
    begin
      if VALID_TRIP_TYPES.include? params[:trip_type]
        response = eval("find_#{params[:trip_type]}_trip_schedule(#{params})")
        result = {trip_details: response[:trip_details], err: response[:err], message: response[:message]}
      else
        result = {trip_details: {}, err: 'err1', message: 'Invalid trip type.'}
      end
    rescue Exception => e
      result = {trip_details: {}, err: 'err007', message: "Something went wrong. Please contact developer.\n\n BACKTRACE: #{e.backtrace}\n\n ERROR MESSAGE: #{e.message}"}
    end

    return result.merge(trip_type: params[:trip_type])
  end


  # Method to find one way trip schedule.
  def self.find_one_way_trip_schedule(params)
    params = recursively_symbolize_params(params)

    return {trip_details: {one_way: {}}, err: 'err0', message: 'Please provide all required fields.'} if params[:origin].blank? or params[:destination].blank? or params[:depart_date].blank?

    trip_data = find_trip_schedule_for_given_date(origin: params[:origin], destination: params[:destination], depart_date: params[:depart_date])

    trip_details = format_trip_schedule(available_train_schedules: trip_data[:trip_details], depart_date: params[:depart_date])


    return {trip_details: {one_way: trip_details}, err: trip_data[:err], message: trip_data[:message]}
  end

  # Method to find return trip schedule
  # ASSUMPTION: For return journey, constraint will be put only return date but not the arrival time of onward journey train
  def self.find_return_trip_schedule(params)
    params = recursively_symbolize_params(params)
    if [params[:origin], params[:destination], params[:depart_date], params[:return_date]].any?(&:blank?)
      return {trip_details: {onward_journey: {}, return_journey: {}}, err: 'err0', message: 'Please provide all required fields.'}
    end

    onward_journey_data = find_trip_schedule_for_given_date(origin: params[:origin], destination: params[:destination], depart_date: params[:depart_date])

    if onward_journey_data[:err].present?
      return {trip_details: {onward_journey: {}, return_journey: {}}, err: onward_journey_data[:err], message: ('ONWARD JOURNEY:' + onward_journey_data[:message])}
    end

    return_journey_data = find_trip_schedule_for_given_date(origin: params[:destination], destination: params[:origin], depart_date: params[:return_date])
    if return_journey_data[:err].present?
      return {trip_details: {onward_journey: {}, return_journey: {}}, err: return_journey_data[:err], message: ('RETURN JOURNEY:' + return_journey_data[:message])}
    end

    onward_trip_details = format_trip_schedule(available_train_schedules: onward_journey_data[:trip_details], depart_date: params[:depart_date], date_constraint: params[:return_date])

    if onward_trip_details[:single_trains].blank? && onward_trip_details[:multi_part].blank?
      return {trip_details: {onward_journey: {}, return_journey: {}}, err: 'err1', message: 'No train combination found for the given date.'}
    end

    return_trip_details = format_trip_schedule(available_train_schedules: return_journey_data[:trip_details], depart_date: params[:return_date])

    return {trip_details: {onward_journey: onward_trip_details, return_journey: return_trip_details}, err: '', message: ''}
  end

  # Method to find multi part trip schedule
  def self.find_multi_part_trip_schedule(params)
    params = recursively_symbolize_params(params)

    if [params[:origin_1], params[:destination_1], params[:origin_2], params[:destination_2], params[:depart_date_1], params[:depart_date_2]].any?(&:blank?)
      return {trip_details: {first_part: {}, second_part: {}}, err: 'err0', message: 'Please provide all required fields.'}
    end

    unless params[:destination_1] == params[:origin_2]
      {trip_details: {first_part: {}, second_part: {}}, err: 'err1', message: 'Destination of first part must be same as origin of second part of multi-part journey.'}
    end

    first_part_data = find_trip_schedule_for_given_date(origin: params[:origin_1], destination: params[:destination_1], depart_date: params[:depart_date_1])

    if first_part_data[:err].present?
      return {trip_details: {first_part: {}, second_part: {}}, err: first_part_data[:err], message: ('FIRST JOURNEY:' + first_part_data[:message])}
    end

    second_part_data = find_trip_schedule_for_given_date(origin: params[:origin_2], destination: params[:destination_2], depart_date: params[:depart_date_2])
    if second_part_data[:err].present?
      return {trip_details: {first_part: {}, second_part: {}}, err: second_part_data[:err], message: ('SECOND JOURNEY:' + second_part_data[:message])}
    end

    first_part_details = format_trip_schedule(available_train_schedules: first_part_data[:trip_details], depart_date: params[:depart_date_1], date_constraint: params[:depart_date_2])

    if first_part_details[:single_trains].blank? && first_part_details[:multi_part].blank?
      return {trip_details: {first_part: {}, second_part: {}}, err: 'err2', message: 'No train combination found for the given dates.'}
    end

    second_part_details = format_trip_schedule(available_train_schedules: second_part_data[:trip_details], depart_date: params[:depart_date_2])

    return {trip_details: {first_part: first_part_details, second_part: second_part_details}, err: '', message: ''}
  end

  # Method to find possible trains for a given origin and destination and departure date
  #
  # <b>Expects</b>
  #   *<b>Hash[:origin]</b> <em>(String)</em> - Valid station code
  #   *<b>Hash[:destination]</b> <em>(String)</em> - Valid station code
  #   *<b>Hash[:depart_date]</b> <em>(String)</em> - Valid depart date
  #
  # <b>Returns</b>
  #   *<b>Hash[:trip_details][:single_trains]</b> <em>(Array)</em> - TrainSchedule Actice Record, origin and destination
  #   *<b>Hash[:trip_details][:multi_part]</b> <em>(Array)</em> - TrainSchedule Actice Record hash with origin, destination in order
  #   *<b>Hash[:err]</b> <em>(String)</em> - Error code
  #   *<b>Hash[:message]</b> <em>(String)</em> - Error message
  #
  # <b>Errors</b>
  #
  # ASSUMPTION:
  #  1. We want maximum upto 2 joining train to reach from origin to destination
  #  2. A train will have same time schedule for all days of week.
  def self.find_trip_schedule_for_given_date(params)
    possible_single_train_schedules, possible_multi_part_train_schedules = [], []
    trip_details = {single_trains: [], multi_part: []}
    if [params[:origin], params[:destination], params[:depart_date]].any?(&:blank?)
      return {trip_details: trip_details, err: 'err11', message: 'Mandatory field missing.'}
    end

    weekday = get_weekday(params[:depart_date])

    possible_origin_trains = TrainSchedule.where("station_code = ? AND #{weekday} = ?", params[:origin], true).all.index_by(&:train_number)

    return {trip_details: trip_details, err: 'err12', message: "No train starting from the given origin station #{params[:origin]} for this date."} if possible_origin_trains.blank?

    possible_destination_trains = TrainSchedule.where("station_code = ? AND distance_from_origin != ?", params[:destination], 0).all.index_by(&:train_number)

    return {trip_details: trip_details, err: 'err13', message: "No train for the given destination #{params[:destination]}."} if possible_destination_trains.blank?

trip_planner/app/controllers/train_schedules_controller.rb
class TrainSchedulesController < ApplicationController
  http_basic_authenticate_with name: "chandan", password: "secrettrip"
  before_action :set_train_schedule, only: [:show, :edit, :update, :destroy]

  # GET /train_schedules
  # GET /train_schedules.json
  def index
    @train_schedules = TrainSchedule.all
  end

  # GET /train_schedules/1
  # GET /train_schedules/1.json
  def show
  end

  # GET /train_schedules/new
  def new
    @train_schedule = TrainSchedule.new
  end

  # GET /train_schedules/1/edit
  def edit
  end

  # POST /train_schedules
  # POST /train_schedules.json
  def create
    @train_schedule = TrainSchedule.new(train_schedule_params)

    respond_to do |format|
      if @train_schedule.save
        format.html { redirect_to @train_schedule, notice: 'Train schedule was successfully created.' }
        format.json { render :show, status: :created, location: @train_schedule }
      else
        format.html { render :new }
        format.json { render json: @train_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /train_schedules/1
  # PATCH/PUT /train_schedules/1.json
  def update
    respond_to do |format|
      if @train_schedule.update(train_schedule_params)
        format.html { redirect_to @train_schedule, notice: 'Train schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @train_schedule }
      else
        format.html { render :edit }
        format.json { render json: @train_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /train_schedules/1
  # DELETE /train_schedules/1.json
  def destroy
    @train_schedule.destroy
    respond_to do |format|
      format.html { redirect_to train_schedules_url, notice: 'Train schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train_schedule
      @train_schedule = TrainSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_schedule_params
      params.require(:train_schedule).permit(:train_number, :station_code, :distance_from_origin, :arrival_time, :departure_time, :sun, :mon, :tue, :wed, :thu, :fri, :sat, :journey_day)
    end
end

trip_planner/app/helpers/train_schedules_helper.rb
module TrainSchedulesHelper
end

trip_planner/app/views/train_schedules/_form.html.erb
<%= form_for(@train_schedule) do |f| %>
  <% if @train_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train_schedule.errors.count, "error") %> prohibited this train_schedule from being saved:</h2>

      <ul>
      <% @train_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :train_number %><br>
    <%= f.number_field :train_number %>
  </div>
  <div class="field">
    <%= f.label :station_code %><br>
    <%= f.text_field :station_code %>
  </div>
  <div class="field">
    <%= f.label :distance_from_origin %><br>
    <%= f.number_field :distance_from_origin %>
  </div>
  <div class="field">
    <%= f.label :arrival_time %><br>
    <%= f.text_field :arrival_time %>
  </div>
  <div class="field">
    <%= f.label :departure_time %><br>
    <%= f.text_field :departure_time %>
  </div>
  <div>
  <div class="field">
    <%= f.label :sun %>
    <%= f.check_box :sun %><br>
  </div>
  <div class="field">
    <%= f.label :mon %>
    <%= f.check_box :mon %><br>
  </div>
  <div class="field">
    <%= f.label :tue %>
    <%= f.check_box :tue %><br>
  </div>
  <div class="field">
    <%= f.label :wed %>
    <%= f.check_box :wed %><br>
  </div>
  <div class="field">
    <%= f.label :thu %>
    <%= f.check_box :thu %><br>
  </div>
  <div class="field">
    <%= f.label :fri %>
    <%= f.check_box :fri %><br>
  </div>
  <div class="field">
    <%= f.label :sat %>
    <%= f.check_box :sat %><br>
  </div>
  </div>
  <div class="field">
    <%= f.label :journey_day %>
    <span style="font-size:10px; color:#ccc;">Specify the days taken to reach this station from origin</span><br>
    <%= f.number_field :journey_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trip_planner/app/views/train_schedules/edit.html.erb
<div id="mainContainer">
  <h1>Editing train_schedule</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @train_schedule %> |
  <%= link_to 'Back', train_schedules_path %>
</div>

trip_planner/app/views/train_schedules/index.html.erb
<div id="mainContainer" style="margin:0px 180px;">
  <h1>Listing train_schedules</h1>

  <table>
    <thead>
    <tr>
      <th>Train number</th>
      <th>Station code</th>
      <th>Distance from origin</th>
      <th>Arrival time</th>
      <th>Departure time</th>
      <th>Sun</th>
      <th>Mon</th>
      <th>Tue</th>
      <th>Wed</th>
      <th>Thu</th>
      <th>Fri</th>
      <th>Sat</th>
      <th>Journey day</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @train_schedules.each do |train_schedule| %>
        <tr>
          <td><%= train_schedule.train_number %></td>
          <td><%= train_schedule.station_code %></td>
          <td><%= train_schedule.distance_from_origin %></td>
          <td><%= train_schedule.arrival_time %></td>
          <td><%= train_schedule.departure_time %></td>
          <td><%= train_schedule.sun %></td>
          <td><%= train_schedule.mon %></td>
          <td><%= train_schedule.tue %></td>
          <td><%= train_schedule.wed %></td>
          <td><%= train_schedule.thu %></td>
          <td><%= train_schedule.fri %></td>
          <td><%= train_schedule.sat %></td>
          <td><%= train_schedule.journey_day %></td>
          <td><%= link_to 'Show', train_schedule %></td>
          <td><%= link_to 'Edit', edit_train_schedule_path(train_schedule) %></td>
          <td><%= link_to 'Destroy', train_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Train schedule', new_train_schedule_path %>
</div>

trip_planner/app/views/train_schedules/new.html.erb
<div id="mainContainer">
  <h1>New train_schedule</h1>

  <%= render 'form' %>

  <%= link_to 'Back', train_schedules_path %>
</div>

trip_planner/app/views/train_schedules/show.html.erb
<div id="mainContainer">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Train number:</strong>
    <%= @train_schedule.train_number %>
  </p>

  <p>
    <strong>Station code:</strong>
    <%= @train_schedule.station_code %>
  </p>

  <p>
    <strong>Distance from origin:</strong>
    <%= @train_schedule.distance_from_origin %>
  </p>

  <p>
    <strong>Arrival time:</strong>
    <%= @train_schedule.arrival_time %>
  </p>

  <p>
    <strong>Departure time:</strong>
    <%= @train_schedule.departure_time %>
  </p>

  <p>
    <strong>Sun:</strong>
    <%= @train_schedule.sun %>
  </p>

  <p>
    <strong>Mon:</strong>
    <%= @train_schedule.mon %>
  </p>

  <p>
    <strong>Tue:</strong>
    <%= @train_schedule.tue %>
  </p>

  <p>
    <strong>Wed:</strong>
    <%= @train_schedule.wed %>
  </p>

  <p>
    <strong>Thu:</strong>
    <%= @train_schedule.thu %>
  </p>

  <p>
    <strong>Fri:</strong>
    <%= @train_schedule.fri %>
  </p>

  <p>
    <strong>Sat:</strong>
    <%= @train_schedule.sat %>
  </p>

  <p>
    <strong>Journey day:</strong>
    <%= @train_schedule.journey_day %>
  </p>

  <%= link_to 'Edit', edit_train_schedule_path(@train_schedule) %> |
  <%= link_to 'Back', train_schedules_path %>
</div>