trip_planner/config/routes.rb
Rails.application.routes.draw do
  resources :train_schedules

  root 'home_page#home'

  get 'trip-type' => 'home_page#get_trip_type', as: 'trip_type'

  get 'search_result-trip' => 'home_page#search_trip', as: 'search_trip'

  resources :trains

  resources :stations

end

trip_planner/app/models/train.rb
class Train < ActiveRecord::Base
  validates :number, presence: true, uniqueness: true

  def self.valid_train_numbers
    all.collect{|train| train.number}
  end
end

trip_planner/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  http_basic_authenticate_with name: "chandan", password: "secrettrip"
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :name)
    end
end

trip_planner/app/helpers/trains_helper.rb
module TrainsHelper
end

trip_planner/app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trip_planner/app/views/trains/edit.html.erb
<div id="mainContainer">
  <h1>Editing train</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @train %> |
  <%= link_to 'Back', trains_path %>
</div>

trip_planner/app/views/trains/index.html.erb
<div id="mainContainer">
  <h1>Listing trains</h1>

  <table>
    <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @trains.each do |train| %>
        <tr>
          <td><%= train.number %></td>
          <td><%= train.name %></td>
          <td><%= link_to 'Show', train %></td>
          <td><%= link_to 'Edit', edit_train_path(train) %></td>
          <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Train', new_train_path %>
</div>

trip_planner/app/views/trains/new.html.erb
<div id="mainContainer">
  <h1>New train</h1>

  <%= render 'form' %>

  <%= link_to 'Back', trains_path %>
</div>

trip_planner/app/views/trains/show.html.erb
<div id="mainContainer">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Number:</strong>
    <%= @train.number %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @train.name %>
  </p>

  <%= link_to 'Edit', edit_train_path(@train) %> |
  <%= link_to 'Back', trains_path %>
</div>